<?php

declare(strict_types=1);

namespace App\Console\Commands;

use App\Models\AcademicYear;
use App\Models\Role;
use App\Models\School;
use App\Models\User;
use App\Services\Academic\DefaultAcademicTerms;
use Carbon\CarbonImmutable;
use Illuminate\Console\Command;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Str;

/**
 * Internal onboarding command for a newly contracted school.
 *
 * This deliberately runs only on the server. It creates no public signup
 * surface, keeps the tenant code generated by the application, and prints a
 * one-time temporary password only when the operator does not supply one.
 */
final class ProvisionSchool extends Command
{
    protected $signature = 'school:provision
        {name : Official school name}
        {admin-email : First administrator email address}
        {--admin-first-name=Administrator : First administrator first name}
        {--admin-last-name= : First administrator last name}
        {--phone= : School telephone number}
        {--address= : School address}
        {--locale=fr : Default locale (fr or en)}
        {--password= : Optional temporary administrator password}';

    protected $description = 'Provision an isolated school tenant and its first administrator';

    public function __construct(private readonly DefaultAcademicTerms $defaultTerms)
    {
        parent::__construct();
    }

    public function handle(): int
    {
        $locale = strtolower((string) $this->option('locale'));
        if (! in_array($locale, ['fr', 'en'], true)) {
            $this->error('The locale must be fr or en.');
            return self::FAILURE;
        }

        $role = Role::query()->where('name', 'administrator')->first();
        if ($role === null) {
            $this->error('Administrator role not found. Run the role and permission seeders first.');
            return self::FAILURE;
        }

        $schoolName = trim((string) $this->argument('name'));
        $email = strtolower(trim((string) $this->argument('admin-email')));
        if ($schoolName === '' || ! filter_var($email, FILTER_VALIDATE_EMAIL)) {
            $this->error('Provide a school name and a valid administrator email address.');
            return self::FAILURE;
        }

        $temporaryPassword = (string) ($this->option('password') ?: Str::password(16));
        if (mb_strlen($temporaryPassword) < 12) {
            $this->error('The temporary password must contain at least 12 characters.');
            return self::FAILURE;
        }

        try {
            [$school, $admin, $year] = DB::transaction(function () use ($schoolName, $email, $locale, $role, $temporaryPassword): array {
                $slug = $this->uniqueSlug($schoolName);
                $school = School::create([
                    'slug' => $slug,
                    'school_name' => $schoolName,
                    'email' => $email,
                    'phone' => $this->option('phone') ?: null,
                    'address' => $this->option('address') ?: null,
                    'default_locale' => $locale,
                ]);

                $startYear = now()->month >= 8 ? now()->year : now()->year - 1;
                $year = AcademicYear::withoutGlobalScopes()->create([
                    'school_id' => $school->id,
                    'title' => sprintf('%d–%d', $startYear, $startYear + 1),
                    'start_date' => CarbonImmutable::create($startYear, 8, 1)->toDateString(),
                    'end_date' => CarbonImmutable::create($startYear + 1, 7, 31)->toDateString(),
                    'status' => AcademicYear::STATUS_ACTIVE,
                ]);
                $school->update(['current_academic_year_id' => $year->id]);
                $this->defaultTerms->provision($year);

                $admin = User::withoutGlobalScopes()->create([
                    'school_id' => $school->id,
                    'role_id' => $role->id,
                    'first_name' => (string) $this->option('admin-first-name'),
                    'last_name' => (string) $this->option('admin-last-name'),
                    'email' => $email,
                    'password' => Hash::make($temporaryPassword),
                    'is_active' => true,
                ]);

                return [$school, $admin, $year];
            });
        } catch (\Throwable $exception) {
            report($exception);
            $this->error('School provisioning could not be completed. No partial school was created.');
            return self::FAILURE;
        }

        $this->newLine();
        $this->info('School provisioned successfully.');
        $this->line('School: ' . $school->school_name);
        $this->line('Sign-in code: ' . $school->access_code);
        $this->line('Administrator: ' . $admin->email);
        $this->line('Academic year: ' . $year->title);
        $this->warn('Temporary password (show once, then share securely): ' . $temporaryPassword);

        return self::SUCCESS;
    }

    private function uniqueSlug(string $name): string
    {
        $base = Str::slug($name) ?: 'school';
        $slug = $base;
        $suffix = 2;

        while (School::query()->where('slug', $slug)->exists()) {
            $slug = $base . '-' . $suffix++;
        }

        return Str::limit($slug, 60, '');
    }
}
