<?php

return [
    'title' => 'Student Report Card', 'student' => 'Student', 'class' => 'Class',
    'admission' => 'Admission #', 'academic_year' => 'Academic Year',
    'date_of_birth' => 'Date of Birth', 'form_master' => 'Form Master',
    'term' => 'Term', 'parent' => 'Parent / Guardian',
    'performance' => 'Academic Performance', 'subject' => 'Subject',
    'code' => 'Code', 'coefficient' => 'Coefficient', 'average' => 'Average / 20',
    'weighted' => 'Weighted', 'no_grades' => 'No published grades for this term yet.',
    'overall' => 'Overall', 'student_average' => 'Student average',
    'class_average' => 'Class average', 'class_rank' => 'Class rank',
    'remark' => 'Performance remark', 'attendance' => 'Attendance',
    'present' => 'Present', 'absent' => 'Absent', 'late' => 'Late',
    'attendance_rate' => 'Attendance rate', 'sessions' => 'sessions recorded',
    'principal' => 'Principal', 'parent_signature' => 'Parent', 'generated' => 'Generated by',
    'academic_decision' => 'Academic decision', 'teacher_appreciation' => 'Teacher appreciation',
    'class_council' => 'Class council recommendation',
];
