'use client';

import { useSearchParams } from 'next/navigation';
import { Printer } from 'lucide-react';
import { PageHeader } from '@/components/ui/PageHeader';
import { Button } from '@/components/ui/Button';
import { Card, CardContent } from '@/components/ui/Card';
import { Skeleton } from '@/components/ui/Skeleton';
import { useSchoolTimetable } from '@/hooks/timetable';
import { DAYS } from '@/types/timetable';
import { useTranslation } from '@/hooks/useTranslation';

export default function SchoolTimetablePage() {
  const { language } = useTranslation();
  const ui = (french: string, english: string) => language === 'fr' ? french : english;
  const academicYearId = useSearchParams().get('year') ?? undefined;
  const { data: slots, isLoading } = useSchoolTimetable(academicYearId);

  if (isLoading) return <Skeleton className="h-96" />;

  return (
    <div>
      <PageHeader
        breadcrumb={[
          { label: ui('Accueil', 'Home'), href: '/admin/dashboard' },
          { label: ui('Emploi du temps', 'Timetable'), href: '/admin/timetable' },
          { label: ui('Emploi du temps général', 'School timetable') },
        ]}
        title={ui('Emploi du temps général', 'School timetable')}
        description={ui('Planning complet de toutes les classes actives.', 'Complete timetable for every active class.')}
        actions={
          <Button variant="outline" leftIcon={<Printer className="h-4 w-4" />} onClick={() => window.print()}>
            {ui('Imprimer / Enregistrer en PDF', 'Print / Save as PDF')}
          </Button>
        }
      />
      <Card>
        <CardContent className="overflow-x-auto py-4">
          <table className="w-full border-collapse text-sm">
            <thead>
              <tr className="bg-secondary-50 text-left">
                <th className="border border-secondary-200 p-2">{ui('Jour', 'Day')}</th>
                <th className="border border-secondary-200 p-2">{ui('Heure', 'Time')}</th>
                <th className="border border-secondary-200 p-2">{ui('Classe', 'Class')}</th>
                <th className="border border-secondary-200 p-2">{ui('Matière', 'Subject')}</th>
                <th className="border border-secondary-200 p-2">{ui('Enseignant', 'Teacher')}</th>
                <th className="border border-secondary-200 p-2">{ui('Salle', 'Room')}</th>
              </tr>
            </thead>
            <tbody>
              {(slots ?? []).map((slot) => (
                <tr key={slot.id}>
                  <td className="border border-secondary-200 p-2">
                    {DAYS.find((day) => day.value === slot.day_of_week)?.label ?? slot.day_of_week}
                  </td>
                  <td className="border border-secondary-200 p-2">{slot.start_time}–{slot.end_time}</td>
                  <td className="border border-secondary-200 p-2 font-medium">{slot.class?.name}</td>
                  <td className="border border-secondary-200 p-2">{slot.subject?.name}</td>
                  <td className="border border-secondary-200 p-2">{slot.teacher?.full_name}</td>
                  <td className="border border-secondary-200 p-2">{slot.room ?? '—'}</td>
                </tr>
              ))}
            </tbody>
          </table>
          {(slots ?? []).length === 0 && (
            <p className="py-12 text-center text-sm text-secondary-500">{ui('Aucun emploi du temps généré n’est encore disponible.', 'No generated timetable is available yet.')}</p>
          )}
        </CardContent>
      </Card>
      <p className="mt-4 hidden text-center text-xs text-secondary-500 print:block">{ui('Généré par CLYVERO ERP', 'Generated by CLYVERO ERP')}</p>
    </div>
  );
}
