'use client';

import { useEffect, useState } from 'react';
import { useQuery } from '@tanstack/react-query';
import { Printer } from 'lucide-react';
import { PageHeader } from '@/components/ui/PageHeader';
import { Button } from '@/components/ui/Button';
import { Card, CardContent } from '@/components/ui/Card';
import { Skeleton } from '@/components/ui/Skeleton';
import { teachersApi } from '@/lib/api/teachers';
import { useTeacherTimetable } from '@/hooks/timetable';
import { DAYS, type DayOfWeek } from '@/types/timetable';
import { useTranslation } from '@/hooks/useTranslation';

export default function TeacherTimetableAdminPage() {
  const { language } = useTranslation();
  const ui = (french: string, english: string) => language === 'fr' ? french : english;
  const { data: teachers, isLoading: loadingTeachers } = useQuery({
    queryKey: ['teachers', 'timetable-view'],
    queryFn: () => teachersApi.list({ per_page: 200 }),
  });
  const [teacherId, setTeacherId] = useState('');
  useEffect(() => {
    if (!teacherId && teachers?.data[0]?.id) setTeacherId(teachers.data[0].id);
  }, [teacherId, teachers]);
  const selectedTeacher = teachers?.data.find((teacher) => teacher.id === teacherId);
  const { data: slots, isLoading: loadingSlots } = useTeacherTimetable(teacherId || undefined);
  const dayLabel = (day: DayOfWeek, fallback: string) => language === 'fr'
    ? ({ monday: 'Lundi', tuesday: 'Mardi', wednesday: 'Mercredi', thursday: 'Jeudi', friday: 'Vendredi', saturday: 'Samedi' } as Record<DayOfWeek, string>)[day]
    : fallback;

  return <div>
    <PageHeader
      breadcrumb={[
        { label: ui('Accueil', 'Home'), href: '/admin/dashboard' },
        { label: ui('Emploi du temps', 'Timetable'), href: '/admin/timetable' },
        { label: ui('Par enseignant', 'By teacher') },
      ]}
      title={ui('Emploi du temps d’un enseignant', 'Teacher timetable')}
      description={ui('Sélectionnez un enseignant pour consulter et imprimer son planning hebdomadaire.', 'Select a teacher to view and print their weekly schedule.')}
      actions={<Button variant="outline" disabled={!teacherId} leftIcon={<Printer className="h-4 w-4" />} onClick={() => window.print()}>{ui('Imprimer / PDF', 'Print / PDF')}</Button>}
    />
    <Card className="mb-6 print:hidden"><CardContent className="py-4">
      <label className="text-sm font-medium text-secondary-700">{ui('Enseignant', 'Teacher')}
        <select value={teacherId} onChange={(event) => setTeacherId(event.target.value)} className="mt-1 h-10 w-full rounded-input border border-secondary-300 bg-surface px-3 md:max-w-lg">
          <option value="">{ui('Sélectionner un enseignant', 'Select a teacher')}</option>
          {(teachers?.data ?? []).map((teacher) => <option key={teacher.id} value={teacher.id}>{teacher.full_name} · {teacher.employee_number}</option>)}
        </select>
      </label>
    </CardContent></Card>
    {(loadingTeachers || loadingSlots) ? <Skeleton className="h-96" /> : <>
      <h2 className="mb-4 text-xl font-semibold text-ink">{selectedTeacher?.full_name ?? ui('Aucun enseignant sélectionné', 'No teacher selected')}</h2>
      <div className="grid gap-4 md:grid-cols-2 lg:grid-cols-3">
        {DAYS.map((day) => {
          const daySlots = (slots ?? []).filter((slot) => slot.day_of_week === day.value);
          return <Card key={day.value}><CardContent className="py-4">
            <h3 className="mb-3 font-semibold text-ink">{dayLabel(day.value, day.label)}</h3>
            <div className="space-y-2">{daySlots.map((slot) => <div key={slot.id} className="rounded-card border border-secondary-200 p-3 text-sm">
              <p className="font-semibold">{slot.subject?.name ?? '—'}</p>
              <p>{slot.start_time}–{slot.end_time}</p>
              <p className="text-secondary-500">{slot.class?.name}{slot.room ? ` · ${ui('Salle', 'Room')} ${slot.room}` : ''}</p>
            </div>)}{daySlots.length === 0 && <p className="text-sm text-secondary-400">{ui('Aucun cours', 'No lessons')}</p>}</div>
          </CardContent></Card>;
        })}
      </div>
      <p className="mt-4 hidden text-center text-xs text-secondary-500 print:block">{ui('Généré par CLYVERO ERP', 'Generated by CLYVERO ERP')}</p>
    </>}
  </div>;
}
