@php($applicationName = config('app.name', 'Clyvero ERP'))

<div class="document-brand-footer">Generated by {{ $applicationName }}</div>

<style>
    .document-brand-footer {
        position: fixed;
        right: 0;
        bottom: 1mm;
        left: 0;
        text-align: center;
        color: #64748b;
        font-family: "DejaVu Sans", sans-serif;
        font-size: 6.5pt;
        font-weight: 600;
        letter-spacing: .35pt;
    }
</style>
